apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-app
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: trial-port
    prometheus.io/scrape: "true"
    sidecar.jaegertracing.io/inject: "true"
  labels:
    name: trial
    release: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
      - name: trial
        image: romran/nd064-c3-trial:latest
        ports:
        - name: trial-port
          containerPort: 8080
          protocol: TCP
        env:
        - name: JAEGER_HOST
          value: my-traces-agent.observability.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: trial-service
spec:
  selector:
    app: trial
  ports:
    - name: trial
      protocol: TCP
      port: 80
      targetPort: trial-port
      nodePort: 30002
  type: NodePort

